### PR TITLE
refactor:  refactoring of the middleware.test.js into refactorMidd…

### PR DESCRIPTION
**Pull request by Cronus1007**
…lewareTest folder
#713 

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
For refactoring of the middleware.test.js

### Breaking Changes
No

### CODE REVIEW

**Comment by Cronus1007** [comment]
Currently working on the refactoring process.
So will add commits accordingly

**Comment by Cronus1007** [comment]
cc @evilebottnawi

**Comment by Cronus1007** [comment]
cc @hiroppy  @evilebottnawi  
#713 Completed

**Comment by Cronus1007** [comment]
@evilebottnawi  @hiroppy

**Comment by alexander-akait** [comment]
Sorry, invalid refactor, please communicate before doing this

**Pull request closed without merging**
