### PR TITLE
Multiple publicPath

### PR DESCRIPTION
**Pull request by reda-alaoui**
**What kind of change does this PR introduce?**

Add the multiple `publicPath` feature.

**Did you add tests for your changes?**

Yes in `API.test.js`

**Summary**

The goal of this PR is to fix issue https://github.com/webpack/webpack-dev-server/issues/945.
This PR is required by PR https://github.com/webpack/webpack-dev-server/pull/943.

`publicPath` option can now be a string or an array of string.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by shellscape** [comment]
Given the solution here: https://github.com/webpack/webpack-dev-server/issues/200#issuecomment-139666063, I'm not sure this is the place for a modification. It looks like webpack-dev-server may be the right place for it.

**Comment by reda-alaoui** [comment]
Hello @shellscape ,

At first, I tried to implement this in webpack-dev-server only by having a list of webpack-dev-middleware. But I came to the conclusion that I would need to pass one separate webpack compiler per publicPath to make it work, which is useless.

Moreover, the comment makes use of multiple `config.output.publicPath`, not multiple `devServer.publicPath`. This is not exactly the same purpose.

This is my first webpack contribution, I may missed something.

**Comment by reda-alaoui** [comment]
You can see, indeed, that the workaround mentionned in the comment creates one webpack compiler per publicPath:
```javascript
configs.forEach(function (config) {
  app.use(middleware(webpack(config), {
    publicPath: config.output.publicPath
  }));
});
```

**Comment by reda-alaoui** [comment]
In fact, both PRs aims to fix webpack/webpack-dev-server#945 rather than webpack/webpack-dev-server#200.

**Comment by reda-alaoui** [comment]
Hello @shellscape ,

Are you expecting an action from me? :)
If yes, which one?

Regards

**Comment by shellscape** [comment]
@reda-alaoui I need to let the other collaborators weigh in on this before it's merged

**Comment by chemzqm** [comment]
I need this feature.  Since I want to have bundle files to be accessed with something like `build/bundle.js` but the html file  which build by `html-webpack-plugin` to be accessed by `/index.html`, there is no way to achieve this with webpack-dev-middleware.

**Comment by reda-alaoui** [comment]
Hello? :)

**Comment by develar** [comment]
@reda-alaoui WDS allows to specify several contentBase (so, for example, it is a solution to serve DLL files in addition to app files (different output dirs)). For what we need several public paths?

**Comment by reda-alaoui** [comment]
@develar, my motivations are exposed in https://github.com/webpack/webpack-dev-server/issues/945
According to my tests, contentBase does not allow to reach my goal.

**Comment by shellscape** [comment]
@reda-alaoui I'm not comfortable pushing this one forward until other webpack collaborators weigh in. don't get me wrong - we greatly appreciate your contribution here - this is just a matter of consensus on a big change. I ping the group periodically, but you could help me get more eyes on this by posting in https://gitter.im/webpack/webpack.

**Comment by reda-alaoui** [comment]
@shellscape , I understand.
But I also know, that PR can be lost in the void when nobody comes periodically to ping.
I can just stop pinging on this one, but I fear it is forgotten.
Moreover, we need this change and don't want to use a forked webpack if there is no certainty that this PR will be merged.

I will take my chance on gitter.

**Comment by shellscape** [comment]
@reda-alaoui I've pinged @TheLarkInn on twitter for some help getting eyes on this.

**Comment by reda-alaoui** [comment]
@shellscape , I did it too 3 days ago.
But no reaction :(

**Comment by kbekkeli** [comment]
_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kbekkeli** [comment]
#

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shellscape** [comment]
After much contemplation and consideration we've decided not to merge this into the codebase. For a more in-depth explanation and further discussion, please see https://github.com/webpack/webpack-dev-server/issues/945.

**Pull request closed without merging**
