### PR TITLE
refactor: code

### PR DESCRIPTION
**Pull request by alexander-akait**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **documentation update**
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

refactor code

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by kumar303** [comment]
Hmm, I am getting a crash on Node `20.11.1` after upgrading `webpack-dev-middleware` to `7.1.0`. Is that Node version supported?

```
┃ node:internal/streams/readable:933
┃   dest.on('unpipe', onunpipe);
┃        ^
┃ TypeError: dest.on is not a function
┃     at ReadStream.Readable.pipe (node:internal/streams/readable:933:8)
┃     at send (/home/.../app/node_modules/webpack-dev-middleware/dist/utils/compatibleAPI.js:270:20)
┃     at processRequest (/home/.../app/node_modules/webpack-dev-middleware/dist/middleware.js:161:7)
┃     at ready (/home/.../app/node_modules/webpack-dev-middleware/dist/utils/ready.js:16:5)
┃     at devMiddlewareInstance (/home/.../app/node_modules/webpack-dev-middleware/dist/middleware.js:48:5)
...
```

**Comment by alexander-akait** [comment]
@kumar303 We support 20.x version, can you create reproducible test repo? We have CI and tests on such version...

**Comment by kumar303** [comment]
Ah, ok, so this is maybe only happening to our application. I'm not sure what's going on or how to reproduce it in isolation. My team is invoking `webpack-dev-middleware` through custom code that looks like it's a compatibility layer for `koa`

<details>
<summary>📄  code</summary>

```tsx
import type {ServerResponse} from 'http';

import type WebpackDevMiddleware from 'webpack-dev-middleware';
import type {Middleware} from 'koa';

const webpackDevMiddlewareKoaPatched = (
  devMiddlewareInstance: ReturnType<typeof WebpackDevMiddleware>,
): Middleware => {
  // create promise reference that resolves when the dev middleware is ready to accept connections,
  // so on subsequent visits, resolving this same promise would yield it's initial fufilled value
  const devMiddlewareReady = new Promise((resolve) => {
    devMiddlewareInstance.waitUntilValid(() => resolve(true));
  });

  return async (ctx, next) => {
    const init = new Promise<void>((resolve) => {
      devMiddlewareInstance(
        ctx.req,
        {
          end: (content: unknown) => {
            ctx.body = content;
            resolve();
          },
          getHeader: ctx.get.bind(ctx),
          setHeader: ctx.set.bind(ctx),
          locals: ctx.state,
        } as unknown as ServerResponse,
        () => resolve(next()),
      );
    });

    await Promise.all([init, devMiddlewareReady]);
  };
};

export default webpackDevMiddlewareKoaPatched;
```

</details>

**Comment by kumar303** [comment]
Calling `devMiddlewareInstance.waitUntilValid()` seems to trigger the error.

**Comment by kumar303** [comment]
This is how we use the [code above](https://github.com/webpack/webpack-dev-middleware/pull/1770#issuecomment-2018341900).

```ts
  import Koa from 'koa'; // 2.15.0
  import webpackDevMiddleware from 'webpack-dev-middleware';
  import webpackDevMiddlewareKoaPatched from '<the code shown two comments above this one>';

  const app = new Koa();

  app.use(
    webpackDevMiddlewareKoaPatched(
      webpackDevMiddleware(multiCompiler, {
        writeToDisk: true,
        stats: 'errors-only',
        publicPath: config.output!.publicPath,
      }),
    ),
  );
```

Is this enough to help? Thanks for taking a look 🙏

**Comment by alexander-akait** [comment]
Investigate your problem

**Comment by alexander-akait** [comment]
The problem is here:
```
{
          end: (content: unknown) => {
            ctx.body = content;
            resolve();
          },
          getHeader: ctx.get.bind(ctx),
          setHeader: ctx.set.bind(ctx),
          locals: ctx.state,
        }
```

Because it is not `ServerResponse`, please use `ctx.res` instead, but I will try to add the official koa support

**Comment by kumar303** [comment]
> `{...} as unknown as ServerResponse`

D'oh. I see this now. Thanks for the second pair of eyes!

**Comment by alexander-akait** [comment]
Not a big problem - https://github.com/webpack/webpack-dev-middleware/pull/1792, most tests were passed, tomorrow I will create `koaWrapper`/improve doc/fix some tests

**Comment by kumar303** [comment]
Just to report back -- we switched to the koa wrapper and it's working great 🎉 Thanks so much.

**Pull request merged**
