### PR TITLE
Add docs around using History API

### LINKED ISSUE #39: Support History API urls
Hey there,

I am using `webpack-dev-middleware` to develop a SPA, with an `index.html` which is programatically generated by webpack. With this plugin, if I navigate to anything other than `/` or `/index.html`, the middleware does not pick up the request, and the request fails.

For most people, something like this solves the problem:

```js
app.get('*', function (req, res) {
  res.send(path.join(__dirname, 'index.html'))
}
```

but for previously mentioned reasons, this doesn't work. I have written this handler to catch urls missed by `webpack-dev-middleware`, but would look at adding this into the core.

```js
app.use(function (req, res, next) {
  if (req.url.match(/^(\/[a-zA-Z-]+)+(.html)?(\?.+)?$/)) { // Just a regex I spun up to sort my use case
    devMiddleware(
      {
        url: '/index.html'
      },
      res,
      next
    )
  } else {
    next()
  }
})
```

Forgive me if I've completely missed a config flag or something - I have looked at the source and couldn't find anything.

I am happy to help write a PR to support this, especially since this will become more popular with `react-transform` becoming more popular.

Thanks for your help in advance

### PR DESCRIPTION
**Pull request by frederickfogerty**
Closes #39

### CODE REVIEW

**Comment by bebraw** [comment]
Can you push those Gist examples below a `examples/` directory? The problem with gists is that they might disappear.

Apart from that this looks good to me.

**Comment by frederickfogerty** [comment]
@bebraw done! :tada:

**Comment by bebraw** [comment]
@sokra Safe to merge?

**Comment by sokra** [comment]
Nope, not safe. It's the wrong way. It's unsafe to read from the webpack filesystem directly. The webpack-dev-middleware is build around to concept that requests block until compilation has finished. Reading directly would bypass this concept.

Instead of requesting from filesystem you should better rewrite the path of the request and give the rewritten request to the webpack-dev-middleware (which handles the blocking). Or just use the `connect-history-api-fallback`, which does exactly that. Just put the webpack-dev-middleware before and after this middleware. (Before to handle the raw request and after to handle the rewritten request)

**Comment by frederickfogerty** [comment]
Funnily enough, that methodology what was I used to before I adopted this
method!

**Comment by nickretallack** [comment]
@sokra can you elaborate on that?  We're supposed to add the webpackDevMiddleware twice?  Should the two instances of it differ?

**Pull request closed without merging**
