### PR TITLE
waitUntilValid function using ready function

### PR DESCRIPTION
**Pull request by bluedaniel**
This is a duplicate of https://github.com/webpack/webpack-dev-middleware/pull/56 but using the ready function as @sokra suggested.

@jantimon deserves credit for the code but I'd like this feature in asap as I need it for building Electron apps locally.

### CODE REVIEW

**Comment by sokra** [comment]
Thanks

**Comment by floross** [comment]
When is the release planned on npm registry ?

**Comment by jantimon** [comment]
I had prepared a pull request which would also move it into the next tick to ensure it's always async.
Are you interested?

**Comment by floross** [comment]
I am.
I am not in the rush to have a publish version of master ;)

**Comment by floross** [comment]
Thanks for the merge ;)

**Pull request merged**
