### PR TITLE
chore(deps): update

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

update deps

### Breaking Changes

No

### Additional Info

Some problems with renovate

### CODE REVIEW

**Comment by ylemkimon** [comment]
Renovate error is due to npm lockfile version mismatch: v6 vs v7.

**Comment by evilebottnawi** [comment]
@ylemkimon yep, I see, I will fix it in the near future, I think renovate should more smart about it

**Comment by ylemkimon** [comment]
It does for Yarn but apparently not for npm. It seems it's possible to set the npm version in the Renovate configuration (`renovate.json`) via [`constraints`](https://docs.renovatebot.com/configuration-options/#constraints) (https://git.io/JkUdY):
```
{
  "constraints": {
    "npm": "^6.0.0"
  }
}
```

**Comment by ylemkimon** [comment]
Actually, Renovate should use npm@6, since 7 is not tagged `latest`. If the error occurs again, could you open an issue at Renovate?

**Pull request merged**
