### PR TITLE
Add progress support

### PR DESCRIPTION
**Pull request by shepherdwind**
Hi, this package is very useful when develop with koa or expressjs.

But, every time server restart, there is a long time console do not output anything. When I use the grunt-webpack, there is progress message, that make me feel more speed.

So, I think this package need progress too.

### CODE REVIEW

**Comment by romseguy** [comment]
Why was this closed? Looks useful to me

**Comment by gpbl** [comment]
Yeah why no progress?

**Comment by rublev** [comment]
+1 - would like compile progress.

**Comment by shepherdwind** [comment]
The project seems no more maintenance .

There is an example below, which have the same effect on my merge request.

```js
const join = require('path').join;
const assign = require('object-assign');
const ProgressPlugin = require('webpack/lib/ProgressPlugin');
const webpack = require('webpack');
const fs = require('fs');
const webpackMiddleware = require('koa-webpack-dev-middleware');
const getPackageName = require('./getPackageName');

module.exports = function() {
  const appName = getPackageName();

  let webpackConfig;
  const webpackConfigFile = join(process.cwd(), 'config/webpack.dev.config.js');
  if (fs.existsSync(webpackConfigFile)) {
    webpackConfig = require(webpackConfigFile);
  } else {
    webpackConfig = require('./webpack.dev.config.js');
  }

  // noInfo only show error message
  const cfg = assign({}, {
    publicPath: '/' + appName + '/',
    noInfo: true,
    progress: true,
  });
  const compiler = webpack(webpackConfig);

  if (cfg.progress) {
    compiler.apply(new ProgressPlugin(function(percentage, msg) {
      const stream = process.stderr;
      if (stream.isTTY && percentage < 0.71) {
        stream.cursorTo(0);
        stream.write(msg);
        stream.clearLine(1);
      } else if (percentage === 1) {
        console.log('\n[chair-webpack]: bundle build is now finished.');
      }
    }));
  }

  return webpackMiddleware(compiler, cfg);
};
```

**Comment by tnguyen14** [comment]
@shepherdwind Can this PR be reopened? The project seems to be active still now?

**Comment by shellscape** [comment]
happy to take a look at it if it is

**Pull request closed without merging**
