### PR TITLE
Only use middleware for 'GET' requests

### PR DESCRIPTION
**Pull request by alexprice91**
Doesn't make sense to for the middleware on all routes.

### CODE REVIEW

**Comment by alexprice91** [comment]
@sokra looks like updates to `middleware` are somewhat slow. I think this is a pretty usual requirement for this package, even if its just for development. Should I fork this repo and work from there instead?

**Comment by SpaceK33z** [comment]
What is the usecase for this?

**Comment by alexprice91** [comment]
Let's say I have an endpoint GET `/login`.
It takes me to a login form and `webpack-dev-middleware` delivers that.

Then I have another endpoint POST `/login`, this endpoint actually logs a user in.

**Comment by SpaceK33z** [comment]
Thanks!

Small feedback thingy for next time: in the commit title, tell why you've changed something, instead of telling what file; we can already see that in the diff.

**Comment by SpaceK33z** [comment]
Released in `1.7.0`.

**Pull request merged**
