### PR TITLE
feat(middleware): add cli options support

### PR DESCRIPTION
**Pull request by EslamHiko**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
solve: https://github.com/webpack/webpack-dev-middleware/issues/312

### Breaking Changes
No

### Additional Info
The unsupported Options: fs,stats,reporter,logger,mimeTypes.

### CODE REVIEW

**Comment by EslamHiko** [comment]
@evilebottnawi did I understood the issue here https://github.com/webpack/webpack-dev-middleware/issues/312 ?

**Comment by hiroppy** [comment]
I agree with @evilebottnawi.

**Comment by EslamHiko** [comment]
@hiroppy okay, I think I misunderstood what the issue was about. as I understand now we can create a config file contains different sets of settings called ex `webpack.middleware.js` and then we can use 2 options ex: `configPath` and `mode` it'll import the settings in the config file with the wanted mode name? so do I understand it clearly now?

**Comment by hiroppy** [comment]
I didn't join this talk but I don' think CLI is necessary. What is the use case for this feature?

**Comment by evilebottnawi** [comment]
No need this here, thanks for the PR

**Pull request closed without merging**
