### PR TITLE
Added "watch" config flag to allow middleware to only compile once

### PR DESCRIPTION
**Pull request by danrspencer**
Also updated docs to include the "filename" option which is used during lazy mode.

### CODE REVIEW

**Comment by sokra** [comment]
There is no watch option. `lazy` means no `watch`.

Could you make it more clear that `filename` is **only** used in lazy mode?

**Comment by danrspencer** [comment]
Adding the watch boolean is to allow both watch and lazy modes to be disabled. E.g. only compile once

I can update the filename docs if necessary but I was just attempting to update the docs to reflect existing functionality, I haven't changed anything around that myself (found on during testing that the undocumented filename option was required otherwise lazy mode didn't work).

**Comment by sokra** [comment]
Why would you compile only once? This looks like an production usecase.

You are correct about the `filename` documentation.

**Comment by danrspencer** [comment]
It is a "production" usecase, however in this case the app is an internal tool where we're with the risks of the dev middlewhere. Flipping the "watch" switch allows us to change between dev and live easily without having to have slightly different code paths between the two.

**Comment by SpaceK33z** [comment]
What @sokra said, this is a production usecase. This middleware is not meant for that.

**Pull request closed without merging**
