### PR TITLE
test: use async API

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

use async-await

### Breaking Changes
no

### Additional Info
no

### CODE REVIEW

**Comment by snitin315** [comment]
strange error on CI

**Comment by snitin315** [comment]
CI fix -https://github.com/webpack/webpack-dev-middleware/pull/1032

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Let's avoid more `done`, for example https://github.com/webpack/webpack-dev-middleware/blob/c9333361ea4ba9bc1879aacc53fbd81635548bd9/test/middleware.test.js#L1225, we need rewrite `listenShorthand` in async function

**Comment by snitin315** [comment]
I will update 👍🏻

**Pull request merged**
