### PR TITLE
refactor: use express recommended api

### PR DESCRIPTION
**Pull request by nuintun**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by hiroppy** [comment]
thanks, but is this necessary changes?

**Comment by nuintun** [comment]
@hiroppy In v4.0.0-rc.3 if I hack with koa:

```js
const expressMiddleware = require('webpack-dev-middleware').default;

module.exports = (compiler, options) => {
  const middleware = expressMiddleware(compiler, options);

  const devMiddleware = async (ctx, next) => {
    const locals = ctx.state;
    const set = ctx.set.bind(ctx);
    const get = ctx.get.bind(ctx);
    const send = content => (ctx.body = content);

    await middleware(ctx.request, { set, get, send, locals, setHeader: set }, next);
  };

  Object.keys(middleware).forEach(key => {
    devMiddleware[key] = middleware[key];
  });

  return devMiddleware;
};
```

`set` and `setHeader` ??

#617 might be a better solution

**Comment by evilebottnawi** [comment]
@nuintun sorry we never support `koa`, if you want to support it, please send a PR with tests too

**Comment by nuintun** [comment]
@evilebottnawi This PR is only for unified API usage, not for compatibility with koa!

https://github.com/webpack/webpack-dev-middleware/blob/49a1203a23b4704853073207421f58ab44502cff/src/middleware.js#L64

https://github.com/webpack/webpack-dev-middleware/blob/49a1203a23b4704853073207421f58ab44502cff/src/utils/handleRangeHeaders.js#L13

**Review by evilebottnawi — APPROVED** [review]
oh, yes, thanks for the PR

**Review by evilebottnawi — APPROVED** [review]
Thanks!

**Pull request merged**
