### PR TITLE
feat: headers support function 'Last-Modified': () => new Date() (#749)

### PR DESCRIPTION
**Pull request by liuxian1990**
#749 I think we can solve this problem in this way

```js
webpackDevMiddleware(compiler, {
  headers: {
    'Last-Modified': () => new Date()
  }
})
```

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I think better to allow `headers` will be `function`

**Comment by liuxian1990** [comment]
Good idea

Can it fit into the schedule

**Comment by alexander-akait** [comment]
Yes, feel free to improve, even more, maybe we can send `req`/`res`/etc as arguments, so you can create more complex things

**Comment by liuxian1990** [comment]
Agree with.

I really need this feature and look forward to the update

**Comment by liuxian1990** [comment]
I don't know much English, and this is my first time to submit PR.

Do you mean I will continue to improve, or you will improve yourself

**Comment by alexander-akait** [comment]
> Do you mean I will continue to improve, or you will improve yourself

You can continue improve, it is easy to implement

**Comment by liuxian1990** [comment]
ok

**Pull request closed without merging**
