### PR TITLE
fix: displayStats only logged

### PR DESCRIPTION
**Pull request by anchengjian**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

image

### Breaking Changes
no Breaking Change

### Additional Info

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks for PR, can you solve lint problems?

**Comment by evilebottnawi** [comment]
Also please accept CLA

**Comment by anchengjian** [comment]
@evilebottnawi done

**Comment by evilebottnawi** [comment]
@anchengjian thanks for PR, will be great create test on this, can you create example with bug?

**Comment by evilebottnawi** [comment]
Great job, thanks!

**Comment by anchengjian** [comment]
@hiroppy Can you help us review this PR ?

**Comment by hiroppy** [comment]
I'm sorry for the late confirmation. Thanks

**Pull request merged**
