### PR TITLE
feat(utils): refactor

### PR DESCRIPTION
**Pull request by jamesgeorge007**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
The respective code snippet appeared redundant atleast IMO

### Breaking Changes
N/A

### Additional Info
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
\cc @hiroppy

**Comment by jamesgeorge007** [comment]
\cc @hiroppy

**Comment by jamesgeorge007** [comment]
\cc @evilebottnawi @hiroppy

**Comment by hiroppy** [comment]
Don't cc every day/every time. Your action is like spam.

Screen Shot 2019-09-02 at 18 19 26

I'm sorry but I am currently busy with my private life and this PR is not a high priority.

**Comment by jamesgeorge007** [comment]
Oops! sincere apologies :pray:

**Comment by hiroppy** [comment]
And actually I agree with this comment. https://github.com/facebook/react/pull/16458#issuecomment-522718684

**Comment by jamesgeorge007** [comment]
It's been a while since I've submitted the respective PR and haven't heard from you guys.

**Comment by hiroppy** [comment]
I closed this pr because we are going to start to work on next branch. Thank you for the effort.

**Pull request closed without merging**
