### PR TITLE
Added charset=UTF-8 to content-type to fix encoding issues.

### PR DESCRIPTION
**Pull request by callumacrae**
Fixes https://github.com/webpack/webpack-dev-server/issues/432

This hasn't broken anything for me.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Could you fix the tests?

**Comment by callumacrae** [comment]
@SpaceK33z: heh, was just pushing the fix when you said that!

**Comment by SpaceK33z** [comment]
Thanks, looks like it doesn't break anything.

**Comment by callumacrae** [comment]
Thanks! 🎉

**Comment by devboxr** [comment]
When can we expect a release including this? Would make testing languages other than English much easier to test (i.e. no building needed).

Thanks!

**Comment by SpaceK33z** [comment]
@devboxr, released `1.8.4`.

**Pull request merged**
