### PR TITLE
chore: drop Node@6, 8

### PR DESCRIPTION
**Pull request by hiroppy**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

I created the `next` branch and dropped Node@6.

### CODE REVIEW

**Comment by hiroppy** [comment]
@evilebottnawi PTAL 🙏

**Comment by hiroppy** [comment]
changed

**Comment by hiroppy** [comment]
Agree with you. Updated.

**Comment by hiroppy** [comment]
I modified babel.config.js.

**Comment by hiroppy** [comment]
@evilebottnawi BTW, currently we don't use `@babel/cli`. So why do we have this package?

**Comment by evilebottnawi** [comment]
@hiroppy yes, will be great to use babel in future (let's do it i next PR)

**Comment by evilebottnawi** [comment]
I have some improvement for azure, i will do it in a next PR

**Comment by hiroppy** [comment]
ok, I'll update the core code with babel.

**Pull request merged**
