### PR TITLE
fix(middleware): do not trigger multiple concurrent rebuilds in lazy mode

### PR DESCRIPTION
**Pull request by MonochromeChameleon**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

Yes

**Summary**

Addresses https://github.com/webpack/webpack-dev-middleware/issues/359

**Does this PR introduce a breaking change?**

I don't think so

**Other information**

It may be that the watchoptions config means that this isn't necessary, in which case feel free to reject :)

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I agree with @evenstensberg

**Comment by MonochromeChameleon** [comment]
My colleague with windows said:

> I've tried those watch options before... they're buggy on docker/windows, where they recognize change (yay) via polling (egh), but they reload the *old* version of the file (boo)
> lazy was the only thing that worked
> very annoying

**Comment by evilebottnawi** [comment]
Closing due inactivity

**Pull request closed without merging**
