### PR TITLE
[WIP] docs(readme): standardize

### PR DESCRIPTION
**Pull request by michael-ciniawsky**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@michael-ciniawsky we decided to return old version README?

**Comment by michael-ciniawsky** [comment]
@montogeek 'Standardize' means to agree upon and ensure markdown support for a common README formatting

**`README`**
```
[![npm][npm]][npm-url]
[![node][node]][node-url]
[![deps][deps]][deps-url]
[![test][test]][test-url]
[![coverage][cover]][cover-url]
[![chat][chat]][chat-url]

<div align="center">
  <h1>My Package</h1>
  <p>Intro/Description</p>
</div>

<h2 align="center">Install</h2>

\```bash
npm i my-package
\```

<h2 align="center">Usage</h2>

### Section

lorem...

<h2 align="center">Options</h2>

|Name|Type|Default|Description|
|:-----:|:---:|:------:|:-----------|
|[**`option`**](#option)|`{Type}`|`''`|lorem...|

### `Option`

lorem....

**`file.ext`**
\```ext

\```

<h2 align="center">Examples</h2>

### Example

lorem...

**`example.ext`**
\```ext

\```


[npm]: https://img.shields.io/npm/v/*.svg
[npm-url]: https://npmjs.com/package/*

[node]: https://img.shields.io/node/v/*.svg
[node-url]: https://nodejs.org

[deps]: https://david-dm.org/webpack-contrib/*.svg
[deps-url]: https://david-dm.org/webpack-contrib/*

[test]: 	https://img.shields.io/circleci/project/github/webpack-contrib/*.svg
[test-url]: https://circleci.com/gh/webpack-contrib/.*

[cover]: https://codecov.io/gh/webpack-contrib/*.svg
[cover-url]: https://codecov.io/gh/webpack-contrib/*

[chat]: https://img.shields.io/badge/gitter-webpack%2Fwebpack-brightgreen.svg
[chat-url]: https://gitter.im/webpack/webpack
```

This is already the used by many repos atm and a former docs maintainer agreed with it and added/ensured support on the docs page. So it should already work... We just want to avoid breaking the site and keep one format to avoid discussions and unnecessary chores :)

**Comment by montogeek** [comment]
It would break the site, it really seems completely unnecessary to use HTML in Markdown.
Markdown is a simple format, keep it like that.

This is adding complexity just for the sake of it:
1. We would have to write another custom Markdown parser just to support that HTML or actually removing it.
2. Another site or integration would try to parse it but it will error out because it has HTML.

**Comment by montogeek** [comment]
https://raw.githubusercontent.com/webpack-contrib/webpack-defaults/master/templates/README.md isn't using it, How all those repos come to agree to that format but the repository that is used as default template don't?

**Comment by montogeek** [comment]
I have no problem at all writing that custom parsing for our docs, but that Readme file would be rendered by dozens of third party sites, for example: GitHub, npm, libraries.io, yarn website, any doc viewer, etc.

**Comment by montogeek** [comment]
Since we are at it, we should make sure every single repo under webpack-contrib follow webpack-defaults configuration and templates.

**Comment by michael-ciniawsky** [comment]
Yes it was changed by `@shellscape`, but we eventually want to revert this change and use the old formating and then stick with it, most repos already use the old format, but he migrated some which are currently broken on the docs page. I'm going to check && update every repo and revert the changes made to `webpack-defaults` once there is consensus on the format

**Pull request closed without merging**
