### PR TITLE
chore: update jest to v29

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **documentation update**
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Deps upgrade. Update jest to v29

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Need rebase :+1:

**Comment by snitin315** [comment]
@alexander-akait Done. Any other breaking change we want to do for this package? Migrate to ESM?

**Comment by alexander-akait** [comment]
@snitin315 Do we resolve all TODO? If yes, I will do release :+1:

**Comment by snitin315** [comment]
@alexander-akait only one TODO is left, but I see it is for webpack and not this package.

https://github.com/webpack/webpack-dev-middleware/blob/e7e3f560b5c7721a4c4f3d92f4c2e8270cbb1d8d/src/index.js#L206-L210

**Comment by alexander-akait** [comment]
@snitin315 it requires some changes on webpcak side, so let's postpone it, also noone ask about this improve in our bug tackers so it is not priority

**Pull request merged**
