### PR TITLE
feat: support `HEAD` method by default

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Support `HEAD` method by default

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by hiroppy** [comment]
🤔 

https://dev.azure.com/webpack/webpack-dev-middleware/_build/results?buildId=2689

```
> webpack-dev-middleware@3.6.2 security /home/vsts/work/1/s
> npm audit

npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2019-05-14T19_07_11_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-middleware@3.6.2 security: `npm audit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-dev-middleware@3.6.2 security script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2019-05-14T19_07_14_437Z-debug.log
##[error]Bash exited with code '1'.
##[section]Finishing: Run NPM audit
```

**Comment by evilebottnawi** [comment]
npm register is very bad

**Comment by hiroppy** [comment]
Thanks!

**Pull request merged**
