### PR TITLE
Update webpack-log dependency to 1.2.0

### LINKED ISSUE #317: Version number of webpack-log dependency is incorrect
Issue #310 rightly pointed out that the version 1.0.1 of webpack-log does not work with webpack-dev-middleware, so "^1.0.1" is an invalid semvar dependency specification for this package. "^1.0.1" indicates that version 1.0.1 should work, which is false. The resolution of "^1.0.1" to a later version of webpack-log on a fresh install is not a valid argument, for multiple reasons:

1. It disregards the semvar specification defining the meaning of the ^ syntax.
2. A fresh install of node_modules should not be required to use webpack-dev-middleware.
3. A project may have already installed version 1.0.1 (or some other version that matches "^1.0.1" yet is incompatible with webpack-dev-middleware), and therefore the correct later version (1.2.0) will not be installed.

As the reporter of #310 (somewhat snarkily) pointed out, this trouble could be avoided by you folks being good stewards of your package.json and updating the version number of webpack-log to match only the versions that are compatible with webpack-dev-middleware.

I will make it easy for you by contributing the PR momentarily.

### PR DESCRIPTION
**Pull request by svicalifornia**
Fixes #317.

### CODE REVIEW

**Comment by svicalifornia** [comment]
So updating a dependency to the version mutually recommended in #310 breaks your test suite. Well, that's fun. I'll have to come back to fix this later, unless someone else can help sooner.

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we fix it in this PR?

**Comment by michael-ciniawsky** [comment]
I think so, but I'm not 💯 sure if the `content-length` check has an important meaning or not, from the test suit it looks like it doesn't (`app.js` is e.g not an injected script by the middleware or the like, just a test `app.js` bundle (which can change in size easily)). I would suggest to update the size to the currently recieved value for now and add a comment that this needs triage anf refactor from our side :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky let's do it, feel free create separate PR for this

**Comment by michael-ciniawsky** [comment]
No 😞 and I just saw you also don't have 🤢...

**Comment by evilebottnawi** [comment]
@michael-ciniawsky waiting for access

**Pull request merged**
