### PR TITLE
remove unnecessary if else

### PR DESCRIPTION
**Pull request by iyuq**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

no extra tests needed.

**Summary**

since the `res.end` method always exists, we can just use it directly.

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by shellscape** [comment]
much appreciate you taking the time to open a PR, but I'm afraid I can't approve this one. that logical block isn't checking if `end` exists, it's checking for `send`, and there was a specific reason for calling `send` if it exists: eb8c505f30ede23c511f88db3597fc959bbfcac2.

**Comment by iyuq** [comment]
why this is necessary? I read the related pr and find out that the commit add this if else for some version will get a res.send is not a function. Here I use res.end for all case, res.end should always exist, so what's the problem?
If I do mistake, please give me more detail which part is wrong.

**Comment by shellscape** [comment]
we don't want to `end` there. we want to `send` and `end` only if the condition exists that `send` is not present.

**Comment by iyuq** [comment]
In what case end here is wrong？What i know from the code is the file of the request url find successfully. if we do not need to add more content to the res, we should end it. if  we cannot end this for some case, i think should add a test case for this.

**Pull request closed without merging**
