### PR TITLE
Add a option, mimeTypes, to support defining custom mime types

### PR DESCRIPTION
**Pull request by xiaoyann**
Please look here https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L65:

```js
res.setHeader("Content-Type", mime.lookup(filename) + "; charset=UTF-8");
```

The line above detemine the mimeType of file, but I have a special file, Index.phtml, so I have to defining custom mimeType

Example:
```js
app.use(webpackMiddleware(webpack({
    // webpack options
    // webpackMiddleware takes a Compiler object as first parameter
    // which is returned by webpack(...) without callback.
    entry: "...",
    output: {
        path: "/"
        // no real path is required, just pass "/"
        // but it will work with other paths too.
    }
}), {
    // ......

    mimeTypes: {
        'text/html': ['phtml']
    }
}));
```

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Please explain your use case.

**Comment by SpaceK33z** [comment]
I seem to have looked over your use case. Could you document this in the README?

**Comment by xiaoyann** [comment]
👌

**Comment by xiaoyann** [comment]
I get it. Thank you.

**Comment by SpaceK33z** [comment]
Hey, I'm planning to release a new version somewhere next week. Do you think you have time to fix this next week? It's no problem if you don't have the time, but just want to know this so I can wait for it ;).

**Comment by shellscape** [comment]
@xiaoyann ping! please see https://github.com/webpack/webpack-dev-middleware/pull/150#pullrequestreview-11779034. would you be able to add a test for this change and move the change to the shared file as requested?

**Comment by xiaoyann** [comment]
@SpaceK33z I have moved the change to the Shared.js and added test.

**Pull request merged**
