### PR TITLE
ci: comment out audit

### PR DESCRIPTION
**Pull request by hiroppy**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy I think we can update `standard-version`

**Comment by hiroppy** [comment]
@evilebottnawi No this is unrelated. See https://github.com/webpack/webpack-dev-middleware/runs/650856219

This cause is another package and we can't fix this even if we run audit fix.

**Comment by hiroppy** [comment]
So we need to merge this PR.

**Comment by evilebottnawi** [comment]
Done

**Pull request merged**
